### ISSUE TITLE
Extended metadata service

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#166]
Resolve below issues using the extended metadata service:

- [x] Timestamp formatting (possibly mm dd HH:mm Z)
- [x] Number (balance, amount) formatting
- [x] "accounts.delegate value" => "accounts.delegate"
- [x] "accounts.delegate setable" => "accounts.delegatable"
- [x] Distinction between **sortable** and **non-sortable** columns

**Comment by anonymoussprocket** [comment]
Sortable is not in the Conseil ticket (for now)

**Comment by anonymoussprocket** [comment]
Closed, unfinished items moved out to separate issues.
